# Site settings
baseurl = "http://www.jackspirou.com/"
languageCode = "en-us"
title = "Jack Spirou"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Jack Spirou"
    description = "About Jack Spirou, a software developer passionate about golang."

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "jack.spirou@me.com"

    [params.navigation]
        brand = "Jack Spirou"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "circle_headshot_transparent.png"
        name = "Jack"
        subtitle = "Coder & Gopher"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Projects"

        [params.portfolio.modal]
            client = "Project"
            date = "Date"
            category = "Technologies"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "I am a software developer located in the St. Paul - Minneapolis area working for Target Corporation as a Tech Lead helping scrum teams build solutions. <br /><br /> I work at a large company, but I am very interested in small startups, new technologies, and agile methodologies."
        right = "Currently I am passionate about Golang and keep up with CoreOS, Docker, HashiCorp, and Google Go products. <br /><br /> I enjoy open source projects, learning new infrastructure tools (CoreOS, Docker, Ansible, Chef), and dabbling in programming language development."

        [params.about.button]
            text = "github.com/jackspirou"
            link = "//github.com/jackspirou"
            icon = "github"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Adress"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "This site is powered by the [Golang](//golang.org) static generator [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["St. Peter Street", "Saint Paul, MN 55102"]

        [params.footer.social]
            title = "On the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/jackspirou"

            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link = "//twitter.com/jack_spirou"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "//linkedin.com/in/jackspirou"


        [params.footer.credits]
            title = "Where I Work"
            text = "Target HQ in downtown Minneapolis, 1000 Nicollet."
